import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    testTimeout: 15_000,
    include: ["tests/**/*.test.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary"],
      thresholds: {
        statements: 90,
        branches: 70,
        functions: 90,
        lines: 90,
      },
      include: [
        "src/id-validator.ts",
        "src/evidence-validator.ts",
        "src/decision-guide-validator.ts",
        "src/claim-derivation-validator.ts",
        "src/relationship-validator.ts",
        "src/markdown-validator.ts",
        "src/security-claim-validator.ts",
        "src/lifecycle-validator.ts",
        "src/registry-consistency-validator.ts",
        "src/graph-projector.ts",
        "src/graph-query.ts",
        "src/graph-artifacts.ts",
        "src/retrieval-units.ts",
        "src/retrieval-query-contract.ts",
        "src/retrieval-query.ts",
        "src/embedding-provider.ts",
        "src/retrieval-evaluation.ts",
        "src/rag-request.ts",
        "src/rag-classification.ts",
        "src/rag-cli-arguments.ts",
        "src/rag-citation-authority.ts",
        "src/rag-context.ts",
        "src/rag-output-contract.ts",
        "src/rag-provider.ts",
        "src/rag-engine.ts",
        "src/rag-evaluation.ts",
      ],
    },
  },
});
